# Generated by Django 4.1.7 on 2023-02-15 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-customer_id'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
    ]
