# Generated by Django 4.1.7 on 2023-02-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_region_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='country',
            new_name='country_name',
        ),
        migrations.AddField(
            model_name='region',
            name='post_code',
            field=models.IntegerField(default=0),
        ),
    ]
