# Generated by Django 4.1.7 on 2023-02-15 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_country_region_country_name_region_post_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
