# Generated by Django 4.1.7 on 2023-02-15 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Details',
            fields=[
                ('order_details_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_quantity', models.IntegerField(default=1)),
                ('product_price', models.IntegerField(default=0)),
                ('sub_total', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='api.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='api.product')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='api.region')),
            ],
            options={
                'verbose_name': 'Order_Details',
                'db_table': 'Order_Details',
                'ordering': ['-order_details_id'],
            },
        ),
    ]
