# Generated by Django 4.1.7 on 2023-02-15 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_order_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='region',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Order_Details',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
